# Generated by Django 6.0.4 on 2026-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Фото URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
