# Generated by Django 6.0.5 on 2026-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_newslettersubscriber_order_orderitem_productrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема листа')),
                ('body_html', models.TextField(verbose_name='Тіло листа (HTML)')),
                ('body_text', models.TextField(blank=True, help_text='Текстова версія для клієнтів без HTML. Заповнюється автоматично якщо порожньо.', verbose_name='Тіло листа (текст)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата відправки')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Кількість отримувачів')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Відправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Кампанія розсилки',
                'verbose_name_plural': 'Кампанії розсилки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оцінка товару', 'verbose_name_plural': 'Оцінки товарів'},
        ),
    ]
